# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/terminado-0.13.1-python_3.10-on-linux_64, last modified Tue Feb  8 12:11:15 2022
# ------------------------------------------------

package:
  name: terminado
  version: 0.13.1
source:
  sha256: 5b82b5c6e991f0705a76f961f43262a7fb1e55b093c16dca83f16384a7f39b7b
  url: https://pypi.io/packages/source/t/terminado/terminado-0.13.1.tar.gz
build:
  number: '0'
  script: /tmp/build/80754af9/terminado_1644322583911/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - brotlipy 0.7.0 py310h7f8727e_1002
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.5.30 py310h06a4308_0
    - cffi 1.15.0 py310hd667e15_1
    - charset-normalizer 2.0.4 pyhd3eb1b0_0
    - cryptography 36.0.0 py310h9ce1e76_0
    - docutils 0.18.1 py310h06a4308_2
    - flit 3.3.0 pyhd3eb1b0_0
    - flit-core 3.3.0 pyhd3eb1b0_0
    - idna 3.3 pyhd3eb1b0_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - pycparser 2.21 pyhd3eb1b0_0
    - pyopenssl 22.0.0 pyhd3eb1b0_0
    - pysocks 1.7.1 py310h06a4308_0
    - python 3.10.0 h12debd9_4
    - readline 8.1.2 h7f8727e_1
    - requests 2.27.1 pyhd3eb1b0_0
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tornado 6.1 py310h7f8727e_0
    - tzdata 2021e hda174b7_0
    - urllib3 1.26.8 pyhd3eb1b0_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - ptyprocess
    - python >=3.10,<3.11.0a0
    - tornado >=4
test:
  commands:
    - pip check
  downstreams:
    - jupyter_server
    - notebook
  imports:
    - terminado
  requires:
    - pip
    - pytest
    - pytest-cov
about:
  description: 'Terminado is a Tornado websocket backend for the term.js Javascript

    terminal emulator library.

    '
  dev_url: https://github.com/takluyver/terminado
  doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
  doc_url: http://terminado.readthedocs.org/en/latest/
  home: https://github.com/jupyter/terminado
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Terminals served by tornado websockets
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - pelson
    - takluyver
