# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Jul 15 18:44:02 2021
# ------------------------------------------------

package:
  name: python-dateutil
  version: 2.8.2
source:
  sha256: 0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86
  url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/python-dateutil_1626374649649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.3 py39h06a4308_0
    - python 3.9.5 h12debd9_4
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - setuptools-scm 6.0.1 pyhd3eb1b0_1
    - setuptools_scm 6.0.1 hd3eb1b0_1
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2021a h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python
    - six >=1.5
test:
  commands:
    - pip check
  imports:
    - dateutil
    - dateutil.parser
    - dateutil.relativedelta
    - dateutil.rrule
    - dateutil.tz
    - dateutil.utils
    - dateutil.zoneinfo
  requires:
    - pip
about:
  description: 'The dateutil module provides powerful extensions to the standard datetime

    module, available in Python.

    '
  dev_url: https://github.com/dateutil/dateutil/
  doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst
  doc_url: https://dateutil.readthedocs.org/en/latest/
  home: https://dateutil.readthedocs.org/
  license: BSD-3-Clause and Apache
  license_family: BSD
  license_file: LICENSE
  summary: Extensions to the standard Python datetime module.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pganssle
