# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/widgetsnbextension-3.5.2-python_3.10-on-linux_64, last modified Fri Feb 11 10:00:16 2022
# ------------------------------------------------

package:
  name: widgetsnbextension
  version: 3.5.2
source:
  sha256: e0731a60ba540cd19bbbefe771a9076dcd2dde90713a8f87f27f53f2d1db7727
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-3.5.2.tar.gz
build:
  number: '0'
  script: /tmp/build/80754af9/widgetsnbextension_1645009354667/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_4
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - notebook >=4.4.1
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
  imports:
    - widgetsnbextension
  requires:
    - pip
about:
  description: 'Interactive HTML widgets for Jupyter notebooks.

    '
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/widgetsnbextension
  doc_url: https://pypi.python.org/pypi/widgetsnbextension
  home: http://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Interactive Widgets for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - jasongrout
    - minrk
    - ocefpaf
    - pbugnion
    - pelson
    - willingc
