# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipython_genutils-0.2.0-on-linux_64, last modified Mon Nov 30 21:54:53 2020
# ------------------------------------------------

package:
    name: ipython_genutils
    version: 0.2.0
source:
    fn: ipython_genutils-0.2.0.tar.gz
    sha256: eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8
    url: https://pypi.io/packages/source/i/ipython_genutils/ipython_genutils-0.2.0.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: pyhd3eb1b0_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.11.8 py36h06a4308_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py36h06a4308_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py36h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - ipython_genutils
        - ipython_genutils.testing
        - ipython_genutils.tests
about:
    description: 'General purpose utilities.

        '
    home: http://ipython.org
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: vestigial utilities from IPython
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - minrk
        - msarahan
        - pelson
        - scopatz
        - takluyver
