# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Jun 22 14:35:49 2022
# ------------------------------------------------

package:
  name: testpath
  version: 0.6.0
source:
  sha256: 2f1b97e6442c02681ebe01bd84f531028a7caea1af3825000f52345c30285e0f
  url: https://pypi.io/packages/source/t/testpath/testpath-0.6.0.tar.gz
build:
  number: '0'
  script: /opt/conda/conda-bld/testpath_1655908557405/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --ignore-installed -vv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.4.26 h06a4308_0
    - certifi 2022.5.18.1 py310h06a4308_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1o h7f8727e_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py310h06a4308_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py310h06a4308_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - sqlite 3.38.3 hc218d9a_0
    - tk 8.6.12 h1ccaba5_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h7f8727e_2
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
  imports:
    - testpath
  requires:
    - pip
about:
  description: 'Testpath contains functions to check things on the filesystem,

    and tools for mocking system commands and recording calls to those.

    '
  dev_url: https://github.com/jupyter/testpath
  doc_url: https://testpath.readthedocs.io
  home: https://testpath.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testpath is a collection of utilities for Python code working with files
    and commands.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1a1a8e9a-149d-4544-9e9d-39e1d8df6386
  recipe-maintainers:
    - minrk
    - ocefpaf
    - takluyver
  remote_url: git@github.com:AnacondaRecipes/testpath-feedstock.git
  sha: 1de59db1bceeb45d26a16f2159f0fc98d869d828
