# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/nbclient-0.5.13-python_3.10-on-linux_64, last modified Mon Apr 18 18:56:16 2022
# ------------------------------------------------

package:
  name: nbclient
  version: 0.5.13
source:
  sha256: 40c52c9b5e3c31faecaee69f202b3f53e38d7c1c563de0fadde9d7eda0fdafe8
  url: https://pypi.io/packages/source/n/nbclient/nbclient-0.5.13.tar.gz
build:
  entry_points:
    - jupyter-execute = nbclient.cli:main
  number: '0'
  script: /tmp/build/80754af9/nbclient_1650290238894/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.3.29 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1n h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py310h06a4308_0
    - sqlite 3.38.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - jupyter_client >=6.1.5
    - nbformat >=5.0
    - nest-asyncio
    - python >=3.10,<3.11.0a0
    - traitlets >=5.0.0
test:
  commands:
    - pip check
    - jupyter-execute --help
  imports:
    - nbclient
  requires:
    - pip
about:
  description: 'NBClient is a tool for parameterizing and executing Jupyter Notebooks.

    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the
    jupyter_client

    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts
    to be run.

    '
  dev_url: https://github.com/jupyter/nbclient
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs
  doc_url: https://nbclient.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - davidbrochart
