# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipykernel-6.9.1-python_3.10-on-linux_64, last modified Fri Mar 11 12:10:41 2022
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.9.1
source:
  sha256: f95070a2dfd3147f8ab19f18ee46733310813758593745e07ec18fb08b409f1d
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.9.1.tar.gz
build:
  number: '0'
  script:
    - /tmp/build/80754af9/ipykernel_1647000775989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      setup.py bdist_wheel
    - cd dist
    - /tmp/build/80754af9/ipykernel_1647000775989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install ipykernel-6.9.1-py3-none-any.whl --no-deps -vv
    - /tmp/build/80754af9/ipykernel_1647000775989/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m ipykernel install --sys-prefix
  script_env:
    - MIGRATING=False
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - backcall 0.2.0 pyhd3eb1b0_0
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - debugpy 1.5.1 py310h295c915_0
    - decorator 5.1.1 pyhd3eb1b0_0
    - entrypoints 0.3 py310h06a4308_0
    - ipython 7.29.0 py310h2f386ee_0
    - jedi 0.18.1 py310h06a4308_1
    - jupyter_client 7.1.2 pyhd3eb1b0_0
    - jupyter_core 4.9.1 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libsodium 1.0.18 h7b6447c_0
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - matplotlib-inline 0.1.2 pyhd3eb1b0_2
    - ncurses 6.3 h7f8727e_2
    - nest-asyncio 1.5.1 pyhd3eb1b0_0
    - openssl 1.1.1m h7f8727e_0
    - parso 0.8.3 pyhd3eb1b0_0
    - pexpect 4.8.0 pyhd3eb1b0_3
    - pickleshare 0.7.5 pyhd3eb1b0_1003
    - pip 21.2.4 py310h06a4308_0
    - prompt-toolkit 3.0.20 pyhd3eb1b0_0
    - ptyprocess 0.7.0 pyhd3eb1b0_2
    - pygments 2.11.2 pyhd3eb1b0_0
    - python 3.10.0 h12debd9_5
    - python-dateutil 2.8.2 pyhd3eb1b0_0
    - pyzmq 22.3.0 py310h295c915_2
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.38.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tornado 6.1 py310h7f8727e_0
    - traitlets 5.1.1 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - wcwidth 0.2.5 pyhd3eb1b0_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zeromq 4.3.4 h2531618_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - debugpy >=1.0.0,<2.0
    - ipython >=7.23.1
    - jupyter_client <8.0
    - matplotlib-inline >=0.1.0,<0.2.0
    - nest-asyncio
    - python >=3.10,<3.11.0a0
    - tornado >=4.2,<7.0
    - traitlets >=5.1.0,<6.0
test:
  commands:
    - pip check
    - jupyter kernelspec list
  imports:
    - ipykernel
  requires:
    - curio
    - flaky
    - ipyparallel
    - matplotlib-base
    - numpy >=1.16.1
    - pip
    - pytest !=5.3.4
    - pytest-cov
    - pytest-timeout
    - trio
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
