# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /home/builder/ktietz/aggregate/webencodings-feedstock/recipe, last modified Thu Aug 20 05:03:29 2020
# ------------------------------------------------

package:
  name: webencodings
  version: 0.5.1
source:
  fn: webencodings-0.5.1.tar.gz
  sha256: 082367f568a7812aa5f6922ffe3d9d027cd83829dc32bcaac4c874eeed618000
  url: https://github.com/gsnedders/python-webencodings/archive/v0.5.1.tar.gz
build:
  number: '1'
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py310h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_4
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python >=3.10,<3.11.0a0
test:
  imports:
    - webencodings
about:
  dev_url: https://github.com/gsnedders/python-webencodings
  doc_url: https://pythonhosted.org/webencodings
  home: https://github.com/gsnedders/python-webencodings
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Character encoding aliases for legacy web content
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jschueller
