# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipywidgets-7.6.5-on-linux_64, last modified Wed Oct 13 14:52:22 2021
# ------------------------------------------------

package:
  name: ipywidgets
  version: 7.6.5
source:
  sha256: 00974f7cb4d5f8d494c19810fedb9fa9b64bffd3cda7c2be23c133a1ad3c99c5
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-7.6.5.tar.gz
build:
  noarch: python
  number: '1'
  script: /tmp/build/80754af9/ipywidgets_1634143127070/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - ipykernel >=4.5.1
    - ipython >=4.0.0
    - jupyterlab_widgets >=1.0.0
    - nbformat >=4.2.0
    - python
    - traitlets >=4.3.1,<6.0.0
    - widgetsnbextension >=3.5.0,<3.6.0
test:
  commands:
    - pip check
  imports:
    - ipywidgets
  requires:
    - pip
about:
  description: 'ipywidgets are interactive HTML widgets for Jupyter notebooks and
    the IPython kernel.

    '
  dev_url: https://github.com/ipython/ipywidgets
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Interactive Widgets
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - jasongrout
    - jtpio
    - maartenbreddels
    - minrk
    - pbugnion
    - pelson
    - willingc
