# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Apr 20 13:42:36 2022
# ------------------------------------------------

package:
  name: beautifulsoup4
  version: 4.11.1
source:
  sha256: ad9aa55b65ef2808eb405f46cf74df7fcb7044d5cbc26487f96eb2ef2e436693
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-4.11.1.tar.gz
build:
  number: '0'
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.3.29 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1n h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py310h06a4308_0
    - sqlite 3.38.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.12 h7f8727e_1
  run:
    - python >=3.10,<3.11.0a0
    - soupsieve >=1.2
test:
  commands:
    - pip check
  imports:
    - bs4
    - bs4.builder
  requires:
    - pip
about:
  description: 'Beautiful Soup is a library for pulling data out of HTML and XML files.

    It provides ways of navigating, searching, and modifying parse trees.

    '
  dev_url: https://code.launchpad.net/beautifulsoup
  doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
  doc_url: https://beautiful-soup-4.readthedocs.io/en/latest/
  home: https://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cf76dd91-39d9-48a2-bda6-c6269453ca15
  recipe-maintainers:
    - jschueller
    - nehaljwani
  remote_url: git@github.com:AnacondaRecipes/beautifulsoup4-feedstock.git
  sha: 95cff0992afa5c0189077940c49633b2805de1bd
