# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri May  7 19:13:46 2021
# ------------------------------------------------

package:
  name: python-fastjsonschema
  version: 2.15.1
source:
  - folder: dist
    sha256: 671f36d225b3493629b5e789428660109528f373cf4b8a22bac6fa2f8191c2d2
    url: https://pypi.io/packages/source/f/fastjsonschema/fastjsonschema-2.15.1.tar.gz
  - folder: src
    sha256: 1a59d7ca91c90b79160ad43859caddb699cad07ddbb91c364a15b1b18f3a1fc4
    url: https://github.com/horejsek/python-fastjsonschema/archive/v2.15.1.tar.gz
build:
  noarch: python
  number: '0'
  script: cd dist && /tmp/build/80754af9/python-fastjsonschema_1620414857593/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.4.13 h06a4308_1
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.4 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.3
test:
  commands:
    - cd src && cd tests && pytest --cov fastjsonschema -k "not compile_to_code_ipv6_regex"
  imports:
    - fastjsonschema
  requires:
    - pytest-benchmark
    - pytest-cov
  source_files:
    - src/tests
about:
  description: 'fastjsonschema implements validation of JSON documents by JSON schema.
    The

    library implements JSON schema drafts 04, 06 and 07. The main purpose is to

    have a really fast implementation.

    '
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs
  doc_url: https://horejsek.github.io/python-fastjsonschema
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
