# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 28 21:30:51 2022
# ------------------------------------------------

package:
  name: pandocfilters
  version: 1.5.0
source:
  fn: pandocfilters-1.5.0.tar.gz
  sha256: 0b679503337d233b4339a817bfc8c50064e2eff681314376a47cb582305a7a38
  url: https://pypi.io/packages/source/p/pandocfilters/pandocfilters-1.5.0.tar.gz
build:
  noarch: python
  number: '0'
  script: pip install --no-deps .
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py39h06a4308_2
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3
test:
  commands:
    - pip check
  imports:
    - pandocfilters
  requires:
    - pip
    - python <3.10
about:
  dev_url: https://github.com/jgm/pandocfilters
  doc_url: https://pandoc.org/filters.html
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python module for writing pandoc filters
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - minrk
