# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Apr 22 10:09:54 2022
# ------------------------------------------------

package:
  name: jupyter_client
  version: 7.2.2
source:
  sha256: 8fdbad344a8baa6a413d86d25bbf87ce21cb2b4aa5a8e0413863b9754eb8eb8a
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-7.2.2.tar.gz
build:
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:RunApp.launch_instance
  number: '0'
  script: /opt/conda/conda-bld/jupyter_client_1650622202839/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.3.29 h06a4308_1
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1n h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py310h06a4308_0
    - sqlite 3.38.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.12 h7f8727e_1
  run:
    - entrypoints
    - jupyter_core >=4.9.2
    - nest-asyncio >=1.5.4
    - python >=3.10,<3.11.0a0
    - python-dateutil >=2.8.2
    - pyzmq >=22.3
    - tornado >=6.0
    - traitlets
test:
  imports:
    - jupyter_client
  requires:
    - codecov
    - coverage
    - ipykernel >=6.5
    - ipython
    - mypy
    - pip
    - pytest
    - pytest-asyncio >=0.18
    - pytest-cov
    - pytest-timeout
about:
  dev_url: https://github.com/jupyter/jupyter_client
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/v7.2.2/docs
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 30f457fc-a31c-403d-884a-7f56bdb57718
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
    - carreau
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/jupyter_client-feedstock.git
  sha: ba7f5cc532d15a5815783bd95d9ce2bc156063bf
