# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Mar 16 13:15:18 2022
# ------------------------------------------------

package:
  name: jinja2
  version: 3.0.3
source:
  fn: Jinja2-3.0.3.tar.gz
  sha256: 611bb273cd68f3b993fabdc4064fc858c5b47a973cb5aa7999ec1ba405c87cd7
  url: https://pypi.io/packages/source/J/Jinja2/Jinja2-3.0.3.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/jinja2_1647436528585/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_5
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.38.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - markupsafe >=2.0
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - jinja2
  requires:
    - pip
about:
  description: 'Jinja2 is a full featured template engine for Python. It has full
    unicode

    support, an optional integrated sandboxed execution environment, widely

    used and BSD licensed.

    '
  dev_url: https://github.com/pallets/jinja
  doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
  doc_url: https://jinja.pocoo.org/docs/dev/
  home: https://jinja.pocoo.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An easy to use stand-alone template engine written in pure python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - nehaljwani
    - scopatz
